Repository 1024pix/pix-nginx-apim, pull requests merged in 2025-01, with the labels that each got.

#4 Update readme
  README.md
Labels: :rocket: Ready to Merge, Tech Review OK, team-captains

#6 [FEATURE] Ajoute une redirection vers la documentation Parcoursup.
  servers.conf.erb
Labels: :rocket: Ready to Merge, team-captains, team-certif

#8 [TECH] Modification de l'url d'acces a l'API Parcoursup (PIX-16090).
  servers.conf.erb
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team, team-captains, team-certif

#9 [FEATURE] Regroupement des endpoints Parcoursup
  servers.conf.erb
Labels: :rocket: Ready to Merge, team-captains, team-certif

#10 [TECH] Parcoursup : configuration compatible API manager pour exposer la documentation (PIX-16304).
  servers.conf.erb
Labels: :rocket: Ready to Merge, team-captains, team-certif
